### ISSUE TITLE
Unable to resubmit sample

### ISSUE THREAD

**Issue by cllde8** [jochenklar/chemotion_REPO#11]
Unable to resubmit sample..

The user is able to resubmit a reaction but not a sample. Please refer to the video https://drive.google.com/file/d/17hn0kyAmSxKJfIWRrza1MCGKl8e-OKK3/view?usp=drive_link for more details.

**Comment by jochenklar** [comment]
This should be fixed by 52b991a8899f5f7d18c5253980320b9ddd2b7a49.

**Comment by jochenklar** [comment]
This is not fixed yet, since used can now resubmit elements which are not under "review".

**Comment by jochenklar** [comment]
I hope this is fixed with 0add672ad4e7f6f97dbb2d66d6795cac63ae4cb6.

**Comment by cllde8** [comment]
Hi,

I tried the re-submit function for the sample, and it works well. Thank you.
