### ISSUE TITLE
Rejecting a new version deletes the element

### ISSUE THREAD

**Issue by jochenklar** [jochenklar/chemotion_REPO#12]
What should happen? Is that ok or should the new version be moved to the new version collection again.

**Comment by cllde8** [comment]
Hi @jochenklar 

If a new version is rejected using the "Reject" button, it should be deleted.

![screenshot-www_chemotion-repository_net-2024_07_30-09_43_21](https://github.com/user-attachments/assets/8b83a28e-c626-434f-9bb2-b6326eeeff6a)

For example,

1. Reaction A is published
2. A new version is created and submitted => Reaction A-V1 is submitted
3. The reviewer rejects Reaction A-V1 => Reaction A-V1 is rejected/deleted
4. A new version is created and submitted => Reaction A-V1 is submitted

**Comment by jochenklar** [comment]
Ok, then I just need to fix the original version and remove the information about the rejected element there as well.

**Comment by jochenklar** [comment]
It is, of course, more complicated. What should happen with the publication? Right now, I run into a problem since the DOI seems to be still reserved. How does it usually works when publications are rejected?

Also, what should happen with Samples of a reaction which got rejected?

**Comment by jochenklar** [comment]
btw, the regular behavoir is kind of weird. If you reject and resubmit a reaction the "second" reaction gets the incremented doi:

```
chemotion_repo_dev=# select doiable_id, suffix from dois where doiable_type = 'Reaction';
 doiable_id |                                   suffix                                   
------------+----------------------------------------------------------------------------
         49 | reaction/SA-FUHFF-UHFFFADPSC-JULLWKBAWZ-UHFFFADPSC-NUHFF-NGRXW-NUHFF-ZZZ
         50 | reaction/SA-FUHFF-UHFFFADPSC-JULLWKBAWZ-UHFFFADPSC-NUHFF-NGRXW-NUHFF-ZZZ.1
(2 rows)
```

**Comment by cllde8** [comment]
Hi,

When a new version is rejected, the submission for this version needs to be rolled back. Consequently, the reservation associated with it should be removed.

**Comment by jochenklar** [comment]
With 7bedbb79a769567d5840333bee5030a25a181fd0 the `element` and the `doi` are destroyed. I kept the `publication`, since the api returns it and I don't know what breaks in the front-end if we remove it as well.

**Comment by cllde8** [comment]
Hi @jochenklar ,

Thank you for addressing this issue. However, I have a concern regarding the use of `original_element.nil?` as a condition in line 105:

https://github.com/jochenklar/chemotion_REPO/blob/7bedbb79a769567d5840333bee5030a25a181fd0/app/models/publication.rb#L105-L111

Could we modify the logic to first identify if this is a case of a new version being rejected, and then remove it from the publication accordingly? Otherwise, please retain the original logic.

Thank you.

**Comment by jochenklar** [comment]
Ok, I changed that to a check of `previous_version` in 4f13ad3eff8acb7f9afdc4c55ff6677e5693bb48. My original idea was that the three methods crash if `original_element` is not there, but now it makes more sense when reading the code, I guess.

**Comment by cllde8** [comment]
Thank you very much. (btw, there is no close button so I cannot close it)
