### ISSUE TITLE
Cannot create a new version for certain samples despite having different DOIs

### ISSUE THREAD

**Issue by cllde8** [jochenklar/chemotion_REPO#13]
Hi,

-------

Cannot create a new version for certain samples despite having different DOIs.

The following link https://chemotion.jochenklar.dev/home/publications/molecules/2112 directs to a page displaying two samples, both published by the same user on different dates and each with a distinct DOI.

Currently, the user can only create a new version for one of the samples; the "Create a new version" button is disabled for the other sample.

A video is at https://drive.google.com/file/d/1nMdiPTziKTimpKJZTyTAWY_lqZ8hgrER/view?usp=drive_link for your reference.

-------

Could you please take a look?

Thank you.

**Comment by jochenklar** [comment]
Hi @cllde8 , I tried to reproduce this, but if I create 2 new samples and publish them and I can create new versions and submit them as expected. There seems to be an already submitted new version for https://chemotion.jochenklar.dev/mydb/scollection/19/sample/678, this one: https://chemotion.jochenklar.dev/mydb/scollection/22/sample/679, was this just an oversight?

**Comment by cllde8** [comment]
Hi @jochenklar , I am unable to reproduce the issue, so it may have been an oversight. Thank you for the clarification.
