### ISSUE TITLE
Blank page while clicking on the sample

### ISSUE THREAD

**Issue by cllde8** [jochenklar/chemotion_REPO#14]
Hi, could you please check the below issue? Thank you very much.

1. refer to #13 

Using the link provided in #13  (https://chemotion.jochenklar.dev/mydb/scollection/22/sample/679) results in a blank page.

2. Log into via account CU3, go to the "Reviewing" collection, select the Sample tab, 

Log in with the CU3 account, navigate to the "Reviewing" collection, and select the Sample tab. Clicking on the 1st, 3rd, and 4th samples displays them properly. However, clicking on the 2nd sample results in a blank page.

![screenshot-chemotion_jochenklar_dev-2024_08_07-14_15_28](https://github.com/user-attachments/assets/49122b22-2aff-4b3f-9343-2f0d31551074)

**Comment by jochenklar** [comment]
This was an oversight in resolving the bug with the resubmit button, it should be fixed in ae712795c6915fd90bcc827a3b619cbab9054422.

**Comment by cllde8** [comment]
Thanks a lot!
