### ISSUE TITLE
Incomplete sample information on the review page

### ISSUE THREAD

**Issue by cllde8** [jochenklar/chemotion_REPO#5]
Submit a new sample with one analysis. Go to the Review page. The analysis part is missing. A screenshot is provided for your reference.

![error_incomplete sample on review page-chemotion_jochenklar_dev-2024_07_22-14_03_43](https://github.com/user-attachments/assets/c890a536-2374-4f43-bb85-c5450d3d4aff)

**Comment by jochenklar** [comment]
I fixed that in f0942ec52a7106dde80d6980ce6bf8b44f3ebf04.

**Comment by cllde8** [comment]
It works perfectly. Thank you.
